services:
  - type: web
    name: mediflux-v3-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_api.py
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /docs
    autoDeploy: true
